
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: user
    ports:
      - 3305:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080